modLoader = "javafml"
loaderVersion = "[45,)"
license = "MIT"
[[mods]]
modId = "infdupe"
version = "${file.jarVersion}"
displayName = "Infinite Duplication"
authors="Maow"
description = '''
Provides magical utilities for ruining the game.
'''
[[dependencies.infdupe]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.infdupe]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"
